version: '3'
services:
  backend:
    image: jose64141/conserjeria-as
    build: ./
    restart: always
    container_name: "conserjeria"
    tty: true
    environment:
      DB_PLATFORM: sqlite
      DB_URL: jdbc:sqlite:conserjeria.db
    ports:
      - "7070:7070"
    networks:
      - private
networks:
  private:
    driver: bridge